const ROUTER = "";

export const ROUTER_NAME = {
  SIGNIN: "signin",
  SIGNUP: "signup",
  FORGOT_PASSWORD: "forgot-password",
  HOME: "home",
  LOCATIONS: "locations",
  LOCATION_DETAIL: "locations/:id",
  LOCATION_BOOKING: "locations/:id/booking",
  PAYMENT_CHECKOUT: "checkout/:token",
  MAP: "map",
  PROFILE: "profile",
  USER_PROFILE: "user/profile",
  USER_BOOKINGS: "user/bookings",
  USER_FAVORITES: "user/favorites",
  CHAT: "chat",
  MY_LOCATIONS: "profile/locations",
  PACKAGE: "profile/package",
};

export const ROUTER_PATH = {
  SIGNIN: `${ROUTER}/${ROUTER_NAME.SIGNIN}`,
  SIGNUP: `${ROUTER}/${ROUTER_NAME.SIGNUP}`,
  FORGOT_PASSWORD: `${ROUTER}/${ROUTER_NAME.FORGOT_PASSWORD}`,
  HOME: `${ROUTER}/${ROUTER_NAME.HOME}`,
  LOCATIONS: `${ROUTER}/${ROUTER_NAME.LOCATIONS}`,
  LOCATION_DETAIL: `${ROUTER}/${ROUTER_NAME.LOCATION_DETAIL}`,
  LOCATION_BOOKING: `${ROUTER}/${ROUTER_NAME.LOCATION_BOOKING}`,
  PAYMENT_CHECKOUT: `${ROUTER}/${ROUTER_NAME.PAYMENT_CHECKOUT}`,
  MAP: `${ROUTER}/${ROUTER_NAME.MAP}`,
  PROFILE: `${ROUTER}/${ROUTER_NAME.PROFILE}`,
  USER_PROFILE: `${ROUTER}/${ROUTER_NAME.USER_PROFILE}`,
  USER_BOOKINGS: `${ROUTER}/${ROUTER_NAME.USER_BOOKINGS}`,
  USER_FAVORITES: `${ROUTER}/${ROUTER_NAME.USER_FAVORITES}`,
  CHAT: `${ROUTER}/${ROUTER_NAME.CHAT}`,
  MY_LOCATIONS: `${ROUTER}/${ROUTER_NAME.MY_LOCATIONS}`,
  PACKAGE: `${ROUTER}/${ROUTER_NAME.PACKAGE}`,
};
