export const MAX_LOCATION_IMAGE_SIZE_MB = 5;
export const MAX_LOCATION_IMAGE_SIZE = MAX_LOCATION_IMAGE_SIZE_MB * 1024 * 1024;
export const MAX_LOCATION_VIDEO_SIZE_MB = 80;
export const MAX_LOCATION_VIDEO_SIZE = MAX_LOCATION_VIDEO_SIZE_MB * 1024 * 1024;
